import { GlossaryTerm } from "./types";

export const glossaryData: GlossaryTerm[] = [
  {
    id: "pda",
    term: "PDA (Program Derived Address)",
    definition: "A Program Derived Address (PDA) is a special type of account address in Solana that is deterministically derived from a program ID and a set of seeds. PDAs are not on the Ed25519 curve, meaning they have no corresponding private key. This makes them ideal for programs to 'own' accounts and sign transactions on behalf of those accounts using Cross-Program Invocations (CPIs). PDAs are fundamental to Solana program architecture, enabling patterns like escrow accounts, vaults, and program-controlled state.",
    shortDefinition: "A deterministic address derived from a program ID and seeds, with no private key.",
    category: "core",
    aliases: ["Program Derived Address"],
    relatedTerms: ["account", "cpi", "seeds", "bump-seed"],
    difficulty: "intermediate",
  },
  {
    id: "account",
    term: "Account",
    definition: "In Solana, everything is an account. Accounts are the fundamental data storage primitive on the network. Each account has an address (public key), a lamport balance, an owner program, and a data field. Accounts can store up to 10MB of data and must maintain a minimum balance (rent-exempt threshold) to persist on-chain. There are several types: system accounts (owned by the System Program), program accounts (containing executable code), and data accounts (storing arbitrary state).",
    shortDefinition: "The fundamental data storage unit in Solana, identified by a public key.",
    category: "core",
    aliases: ["Solana Account"],
    relatedTerms: ["pda", "rent", "lamport", "system-program"],
    difficulty: "beginner",
  },
  {
    id: "poh",
    term: "Proof of History (PoH)",
    definition: "Proof of History is Solana's innovative timekeeping mechanism that creates a historical record proving that an event occurred at a specific moment in time. It uses a sequential-hashing Verifiable Delay Function (VDF) to create a cryptographic timestamp. PoH is not a consensus mechanism itself but rather a clock that helps validators agree on the ordering of events without extensive communication, dramatically reducing consensus overhead and enabling Solana's high throughput of up to 65,000 TPS.",
    shortDefinition: "Solana's cryptographic clock that proves events occurred at specific times.",
    category: "consensus",
    aliases: ["PoH"],
    relatedTerms: ["tower-bft", "validator", "slot", "block"],
    difficulty: "intermediate",
  },
  {
    id: "tower-bft",
    term: "Tower BFT",
    definition: "Tower BFT is Solana's custom implementation of Practical Byzantine Fault Tolerance (PBFT), optimized using Proof of History as a clock. It reduces messaging overhead by leveraging PoH's cryptographic timestamps, allowing validators to vote on the state of the ledger with minimal communication. Validators stake SOL and vote on forks, with exponentially increasing lockout periods for older votes, ensuring network convergence and finality.",
    shortDefinition: "Solana's PoH-optimized Byzantine Fault Tolerance consensus mechanism.",
    category: "consensus",
    aliases: ["TowerBFT"],
    relatedTerms: ["poh", "validator", "slot", "finality"],
    difficulty: "advanced",
  },
  {
    id: "validator",
    term: "Validator",
    definition: "A validator is a node in the Solana network that participates in consensus by verifying transactions, producing blocks, and voting on the state of the blockchain. Validators run the Solana validator software, stake SOL tokens, and earn rewards for their participation. They process transactions, maintain a copy of the ledger, and help secure the network through stake-weighted voting in Tower BFT consensus.",
    shortDefinition: "A network node that verifies transactions and participates in consensus.",
    category: "consensus",
    aliases: ["Validator Node"],
    relatedTerms: ["tower-bft", "stake", "slot", "leader-schedule"],
    difficulty: "beginner",
  },
  {
    id: "cpi",
    term: "Cross-Program Invocation (CPI)",
    definition: "A Cross-Program Invocation allows one Solana program to call another program's instructions within a single transaction. CPIs enable composability — the ability for programs to interact and build on each other. When a CPI is made, the callee program runs with the caller's privileges and the accounts passed to it. CPIs have a depth limit of 4 and are essential for building complex DeFi protocols and composable applications.",
    shortDefinition: "A mechanism for one Solana program to call another program's instructions.",
    category: "development",
    aliases: ["CPI"],
    relatedTerms: ["pda", "instruction", "program", "composability"],
    difficulty: "intermediate",
  },
  {
    id: "rent",
    term: "Rent",
    definition: "Rent is the cost of storing data on the Solana blockchain. Every account must maintain a minimum lamport balance proportional to its data size to remain active. If an account's balance falls below the rent-exempt threshold, it may be purged by the runtime. Since the introduction of rent exemption, most accounts maintain a balance above this threshold (approximately 0.00089 SOL per byte per year equivalent), effectively making storage a one-time cost.",
    shortDefinition: "The cost of maintaining data storage on Solana, typically paid as a one-time deposit.",
    category: "core",
    aliases: ["Storage Rent", "Rent Exemption"],
    relatedTerms: ["account", "lamport", "rent-exempt"],
    difficulty: "beginner",
  },
  {
    id: "lamport",
    term: "Lamport",
    definition: "A lamport is the smallest unit of SOL, Solana's native token. One SOL equals 1,000,000,000 (one billion) lamports. Named after Leslie Lamport, a computer scientist known for his work on distributed systems. Lamports are used throughout the Solana runtime for expressing account balances, transaction fees, and rent costs.",
    shortDefinition: "The smallest unit of SOL (1 SOL = 1 billion lamports).",
    category: "core",
    aliases: ["Lamports"],
    relatedTerms: ["sol", "rent", "transaction-fee"],
    difficulty: "beginner",
  },
  {
    id: "amm",
    term: "AMM (Automated Market Maker)",
    definition: "An Automated Market Maker is a decentralized exchange mechanism that uses mathematical formulas to price assets in liquidity pools instead of traditional order books. On Solana, popular AMMs like Raydium, Orca, and Jupiter use constant product (x*y=k) or concentrated liquidity models. Users provide liquidity to pools and earn fees, while traders swap tokens against these pools. Solana's high speed and low fees make it ideal for AMM operations.",
    shortDefinition: "A DEX mechanism using liquidity pools and algorithms for token pricing.",
    category: "defi",
    aliases: ["Automated Market Maker", "DEX"],
    relatedTerms: ["liquidity-pool", "swap", "slippage", "token"],
    difficulty: "intermediate",
  },
  {
    id: "slot",
    term: "Slot",
    definition: "A slot is a period of time (approximately 400 milliseconds) during which a validator can produce a block. Slots are the basic unit of time in Solana's consensus mechanism. Not every slot produces a block — a slot may be skipped if the designated leader validator is offline. Slots are grouped into epochs (432,000 slots each, approximately 2-3 days), which determine the leader schedule and staking rewards distribution.",
    shortDefinition: "A ~400ms time window in which a validator can produce a block.",
    category: "consensus",
    aliases: ["Block Slot"],
    relatedTerms: ["block", "epoch", "leader-schedule", "validator"],
    difficulty: "beginner",
  },
  {
    id: "spl-token",
    term: "SPL Token",
    definition: "SPL (Solana Program Library) Token is the standard for fungible and non-fungible tokens on Solana, analogous to ERC-20/ERC-721 on Ethereum. The SPL Token program defines a common implementation for creating, minting, transferring, and burning tokens. Each SPL token has a mint account (defining supply and decimals) and associated token accounts (holding balances for each owner). The Token-2022 program extends this with features like transfer fees and confidential transfers.",
    shortDefinition: "Solana's standard token program for creating fungible and non-fungible tokens.",
    category: "token",
    aliases: ["SPL", "Solana Token"],
    relatedTerms: ["mint", "token-account", "token-2022", "metaplex"],
    difficulty: "beginner",
  },
  {
    id: "anchor",
    term: "Anchor Framework",
    definition: "Anchor is the most popular framework for building Solana programs (smart contracts). It provides a Rust-based DSL (Domain Specific Language) that abstracts away much of the boilerplate code required for Solana development, including account serialization/deserialization, instruction dispatch, and constraint validation. Anchor also generates IDL (Interface Description Language) files and TypeScript client libraries, making it easier to interact with programs from the frontend.",
    shortDefinition: "The leading Rust framework for building Solana smart contracts.",
    category: "development",
    aliases: ["Anchor", "Anchor Lang"],
    relatedTerms: ["program", "idl", "cpi", "pda"],
    difficulty: "intermediate",
  },
  {
    id: "program",
    term: "Program",
    definition: "A program in Solana is equivalent to a smart contract on other blockchains. Programs are stateless executable code deployed to the network that process instructions. They are stored in special accounts marked as executable and are owned by the BPF Loader. Programs can read and modify the data of accounts they own. Popular programs include the System Program, Token Program, and Associated Token Account Program. Custom programs are typically written in Rust using the Anchor framework.",
    shortDefinition: "Solana's equivalent of a smart contract — stateless executable code on-chain.",
    category: "development",
    aliases: ["Smart Contract", "On-chain Program"],
    relatedTerms: ["anchor", "instruction", "cpi", "bpf"],
    difficulty: "beginner",
  },
  {
    id: "instruction",
    term: "Instruction",
    definition: "An instruction is the smallest unit of execution in a Solana transaction. Each instruction specifies a program to invoke, the accounts to pass, and the input data. A single transaction can contain multiple instructions that execute atomically — either all succeed or all fail. Instructions define what a program should do, such as transferring SOL, creating an account, or swapping tokens.",
    shortDefinition: "The smallest execution unit in a transaction, specifying a program call and its data.",
    category: "core",
    aliases: ["IX", "Transaction Instruction"],
    relatedTerms: ["transaction", "program", "account", "cpi"],
    difficulty: "beginner",
  },
  {
    id: "transaction",
    term: "Transaction",
    definition: "A transaction is a signed message containing one or more instructions that are executed atomically on Solana. Transactions include a recent blockhash (for deduplication and expiry), one or more signatures, and a list of instructions. They have a maximum size of 1,232 bytes. Versioned transactions (v0) support Address Lookup Tables for including more accounts. Transactions are processed by validators and included in blocks.",
    shortDefinition: "A signed, atomic batch of instructions executed on the Solana network.",
    category: "core",
    aliases: ["TX"],
    relatedTerms: ["instruction", "blockhash", "signature", "versioned-transaction"],
    difficulty: "beginner",
  },
  {
    id: "stake",
    term: "Staking",
    definition: "Staking on Solana involves delegating SOL tokens to a validator to help secure the network and earn rewards. Stakers create stake accounts, delegate to validators, and receive a share of the validator's rewards proportional to their stake. The staking yield varies but typically ranges from 6-8% APY. Stake accounts have warming-up and cooling-down periods, and delegators can redelegate to different validators at any time.",
    shortDefinition: "Delegating SOL to validators to secure the network and earn rewards.",
    category: "consensus",
    aliases: ["Stake", "Delegation", "Staking SOL"],
    relatedTerms: ["validator", "epoch", "stake-account", "sol"],
    difficulty: "beginner",
  },
  {
    id: "liquidity-pool",
    term: "Liquidity Pool",
    definition: "A liquidity pool is a collection of tokens locked in a smart contract that facilitates decentralized trading, lending, and other DeFi activities. On Solana, liquidity pools power AMMs like Raydium and Orca. Liquidity providers (LPs) deposit token pairs into pools and receive LP tokens representing their share. They earn trading fees but face risks like impermanent loss. Concentrated liquidity pools (like Orca Whirlpools) allow LPs to concentrate their capital in specific price ranges.",
    shortDefinition: "A smart contract holding paired tokens that enables decentralized trading.",
    category: "defi",
    aliases: ["LP", "Pool"],
    relatedTerms: ["amm", "swap", "impermanent-loss", "lp-token"],
    difficulty: "intermediate",
  },
  {
    id: "sol",
    term: "SOL",
    definition: "SOL is the native token of the Solana blockchain. It is used for paying transaction fees, staking with validators, and as the base currency for DeFi applications on the network. SOL has a current inflation schedule starting at 8% annually, decreasing by 15% each year until reaching a long-term rate of 1.5%. The token's smallest unit is the lamport (1 SOL = 1 billion lamports).",
    shortDefinition: "Solana's native cryptocurrency used for fees, staking, and DeFi.",
    category: "core",
    aliases: ["Solana Token"],
    relatedTerms: ["lamport", "stake", "transaction-fee"],
    difficulty: "beginner",
  },
  {
    id: "seeds",
    term: "Seeds",
    definition: "Seeds are byte arrays used in combination with a program ID to derive Program Derived Addresses (PDAs). Seeds can be any combination of static strings, public keys, or other data that uniquely identifies the account being derived. Common seed patterns include using a string prefix with a user's public key, enabling deterministic account lookups without storing addresses. The findProgramAddress function iterates through bump seeds (255 to 0) to find a valid off-curve address.",
    shortDefinition: "Byte arrays combined with a program ID to deterministically derive PDA addresses.",
    category: "development",
    aliases: ["PDA Seeds"],
    relatedTerms: ["pda", "bump-seed", "account"],
    difficulty: "intermediate",
  },
  {
    id: "bump-seed",
    term: "Bump Seed",
    definition: "A bump seed (or bump) is a single byte (0-255) appended to PDA seeds to ensure the derived address falls off the Ed25519 curve. The findProgramAddress function tries bump values from 255 down to 0, returning the first valid PDA. The canonical bump is the highest value that produces a valid off-curve address. Storing and reusing the bump is a common optimization to avoid recomputing it.",
    shortDefinition: "A byte value that ensures a PDA falls off the Ed25519 elliptic curve.",
    category: "development",
    aliases: ["Bump", "Nonce"],
    relatedTerms: ["pda", "seeds", "account"],
    difficulty: "advanced",
  },
  {
    id: "epoch",
    term: "Epoch",
    definition: "An epoch is a period of approximately 2-3 days (432,000 slots) in Solana during which the leader schedule is fixed and staking rewards are calculated. At the start of each epoch, the leader schedule is determined based on the stake distribution, and at the end, rewards are distributed to validators and their delegators. Epoch boundaries are also when stake activations and deactivations take effect.",
    shortDefinition: "A ~2-3 day period defining leader schedules and reward distribution cycles.",
    category: "consensus",
    aliases: ["Staking Epoch"],
    relatedTerms: ["slot", "validator", "stake", "leader-schedule"],
    difficulty: "intermediate",
  },
  {
    id: "swap",
    term: "Token Swap",
    definition: "A token swap is the exchange of one token for another using a decentralized exchange protocol. On Solana, swaps are facilitated by AMMs and DEX aggregators like Jupiter, which routes trades across multiple liquidity sources to find the best price. Swaps involve specifying input/output tokens, slippage tolerance, and optional parameters like priority fees for faster execution.",
    shortDefinition: "Exchanging one token for another through decentralized exchange protocols.",
    category: "defi",
    aliases: ["Swap", "Token Exchange"],
    relatedTerms: ["amm", "liquidity-pool", "slippage", "jupiter"],
    difficulty: "beginner",
  },
  {
    id: "mint",
    term: "Mint Account",
    definition: "A mint account is a special SPL Token account that defines a token's properties: total supply, number of decimals, and mint/freeze authorities. Each unique token on Solana has exactly one mint account. The mint authority can create new tokens, while the freeze authority can freeze token accounts. Renouncing these authorities makes the token immutable. NFTs are tokens with a supply of 1 and 0 decimals.",
    shortDefinition: "An account defining a token's supply, decimals, and authorities.",
    category: "token",
    aliases: ["Token Mint", "Mint"],
    relatedTerms: ["spl-token", "token-account", "nft"],
    difficulty: "intermediate",
  },
  {
    id: "nft",
    term: "NFT (Non-Fungible Token)",
    definition: "An NFT on Solana is an SPL token with a supply of 1 and 0 decimals, making it unique and indivisible. Solana NFTs use the Metaplex standard for metadata, which includes name, symbol, URI (pointing to off-chain JSON), and optional on-chain attributes. Compressed NFTs (cNFTs) use state compression and Merkle trees to dramatically reduce minting costs. Collections group related NFTs under a verified collection address.",
    shortDefinition: "A unique, indivisible token on Solana, typically following the Metaplex standard.",
    category: "token",
    aliases: ["Non-Fungible Token", "Digital Collectible"],
    relatedTerms: ["spl-token", "mint", "metaplex", "compressed-nft"],
    difficulty: "beginner",
  },
  {
    id: "idl",
    term: "IDL (Interface Description Language)",
    definition: "An IDL in Solana (specifically Anchor) is a JSON specification that describes a program's interface — its instructions, accounts, types, and errors. The IDL is automatically generated by the Anchor framework from program code and serves as a contract between the on-chain program and off-chain clients. TypeScript clients use the IDL to generate type-safe program interaction methods, enabling auto-completion and compile-time error checking.",
    shortDefinition: "A JSON specification describing a Solana program's interface and data types.",
    category: "development",
    aliases: ["Interface Definition"],
    relatedTerms: ["anchor", "program", "instruction"],
    difficulty: "intermediate",
  },
  {
    id: "composability",
    term: "Composability",
    definition: "Composability refers to the ability of different programs and protocols on Solana to interact and build upon each other seamlessly. Thanks to CPIs and Solana's single-state machine architecture, any program can call any other program within a transaction. This enables complex DeFi strategies like flash loans, yield aggregation, and multi-hop swaps to execute atomically in a single transaction, often called 'money legos.'",
    shortDefinition: "The ability of Solana programs to interact and build upon each other seamlessly.",
    category: "development",
    aliases: ["Money Legos", "DeFi Composability"],
    relatedTerms: ["cpi", "instruction", "transaction", "defi"],
    difficulty: "intermediate",
  },
  {
    id: "turbine",
    term: "Turbine",
    definition: "Turbine is Solana's block propagation protocol, inspired by BitTorrent. It breaks blocks into smaller packets called 'shreds' and distributes them across the network using a tree-like structure of neighborhoods. This approach allows Solana to propagate blocks efficiently without requiring every validator to download the entire block from a single source, significantly reducing bandwidth requirements and improving block propagation speed.",
    shortDefinition: "Solana's BitTorrent-inspired block propagation protocol using shredded data.",
    category: "networking",
    aliases: ["Block Propagation"],
    relatedTerms: ["validator", "block", "shred", "gulf-stream"],
    difficulty: "advanced",
  },
  {
    id: "gulf-stream",
    term: "Gulf Stream",
    definition: "Gulf Stream is Solana's mempool-less transaction forwarding protocol. Instead of maintaining a traditional mempool, transactions are forwarded to the expected next few leaders before their slots arrive. This reduces confirmation times and memory pressure on validators, as transactions are pre-cached at the next leader rather than sitting in a shared mempool. It's one of the key innovations enabling Solana's sub-second finality.",
    shortDefinition: "Solana's mempool-less protocol that forwards transactions to upcoming leaders.",
    category: "networking",
    aliases: ["Transaction Forwarding"],
    relatedTerms: ["validator", "leader-schedule", "slot", "turbine"],
    difficulty: "advanced",
  },
  {
    id: "sealevel",
    term: "Sealevel",
    definition: "Sealevel is Solana's parallel smart contract runtime. Unlike Ethereum's sequential EVM, Sealevel can process thousands of contracts in parallel by analyzing transaction account dependencies at runtime. Transactions that don't touch the same accounts can execute simultaneously across multiple cores. This parallelism is a key factor in Solana's high throughput and is enabled by requiring transactions to declare their account dependencies upfront.",
    shortDefinition: "Solana's parallel runtime engine that executes non-conflicting transactions simultaneously.",
    category: "core",
    aliases: ["Parallel Runtime"],
    relatedTerms: ["transaction", "account", "validator"],
    difficulty: "advanced",
  },
  {
    id: "finality",
    term: "Finality",
    definition: "Finality on Solana refers to the point at which a transaction is considered irreversible. Solana offers multiple levels of finality: 'processed' (transaction executed), 'confirmed' (voted on by supermajority), and 'finalized' (rooted, ~31 confirmations). Optimistic confirmation provides fast finality (~400ms) with high probability, while full finality takes approximately 6-12 seconds. This is significantly faster than most other blockchains.",
    shortDefinition: "The irreversible confirmation of a transaction, achieved in ~400ms to 12 seconds.",
    category: "consensus",
    aliases: ["Transaction Finality"],
    relatedTerms: ["slot", "tower-bft", "validator", "block"],
    difficulty: "intermediate",
  },
];
